name: CI Build

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build-client-and-server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      # ---------- SERVER ----------
      - name: Install Server deps
        working-directory: ./server
        run: npm install

      - name: Lint Server
        working-directory: ./server
        run: npm run lint --if-present

      - name: Test Server
        working-directory: ./server
        run: npm test --if-present

      # Optional build server if ts compiled
      - name: Build Server
        working-directory: ./server
        run: npm run build --if-present
